### ISSUE TITLE
storage configuration page throws errors

### ISSUE THREAD

**Issue by zipymonkey** [psu-libraries/storagemodule#5]
Replacing https://github.com/psu-libraries/dsf-web/issues/41.

## Steps to Duplicate
* Go to Configuration => Content Authoring => Storage (https://dsf-web.psul.localhost/admin/config/content/storage)
* You will see an WSOD and the following error message in logs:

> InvalidArgumentException: Class "\Drupal\storage\Form\StorageSettingsForm" does not exist. in Drupal\Core\DependencyInjection\ClassResolver->getInstanceFromDefinition() (line 37 of /var/www/html/web/core/lib/Drupal/Core/DependencyInjection/ClassResolver.php).

## Technical Details
This is because the Filename and Class name do not match (case mismatch).  Classes should be CamelCase so the file needs to be renamed to StorageSettingsForm.  This could be an issue on MacOS since its filesystem is not really case sensitive.

<img width="564" alt="Screenshot 2024-11-22 at 8 34 36 AM" src="https://github.com/user-attachments/assets/9c328318-157a-4770-87a8-f01a4ba7f76a">

**Comment by chrisdarke42** [comment]
changed the file name within the repo as it was able to cope with the case sensitive change

**Comment by chrisdarke42** [comment]
Released to finish off the issue in dsf
