### ISSUE TITLE
Replace Font Awesome Icons

### ISSUE THREAD

**Issue by zipymonkey** [psu-libraries/storagemodule#8]
There are only a handful of Font Awesome icons being used so requiring the entire FA library is unnecessary.  This is also contributing the low lighthouse performance score. 

## Icons Used:
- fa-info-circle
- fa-arrow-right
- fa-comments
- fa-circle
- fa-circle-check

These could all be replaced with individual SVGs files (either from font-awesome or another library) and that would save ~23Kb of css and ~300Kb of fonts.

**Comment by chrisdarke42** [comment]
@zipymonkey  please review, then I can get the dsf side updated
